pipeline {
  agent any
  options {
    timeout(time: 3, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm install'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm test'
      }
    }
  }
}
